interface ConnCommsRctiline {
      uniqueId: string,
      deletedByDisplay: any,
      parentType: any,
      parentId: string,
      associateId: string,
      introducer: string,
      lender: string,
      lenderNameShort: string,
      loanName: string,
      loanAmount: number,
      loanBalance: number,
      dateSettled: number,
      commission: number,
      gst: number,
      total: number,
      commissionType: string,
      accountNumber: string,
      commissionPercent: number,
      commissionPaid: number,
      gstPaid: number,
      totalPaid: number,
      comments: string,
      associateName: string
}

interface ConnCommsRcti {
  totalCount: number,
  count: number,
  offset: number,
  results: ConnCommsRctiline[],
  uniqueId: string,
  company: string,
  isDeleted: any,
  deletedBy: string,
  deletedByDisplay: any,
  deletedOn: number,
  createdOn: number,
  createdBy: string,
  isNew: any,
  parentType: any,
  parentId: string,
  batchId: string,
  introducerId: string,
  ownerId: string,
  name: string,
  startDate: number,
  endDate: number,
  paymentDate: number,
  totalUFC: number,
  totalTC: number,
  totalGST: number,
  totalAmount: number,
  taxedUFC: number,
  taxFreeUFC: number,
  taxedTC: number,
  taxFreeTC: number,
  ufcGST: number,
  tcGST: number,
  adjustments: number,
  lines: number,
  addressBlock: string,
  bsb: string,
  accountName: string,
  accountNumber: string,
  bank: string,
  commissionPlan: string,
  status: string,
  type: string,
  invoiceId: string,
  totalCAFComms: any,
  totalCAFDeductions: any,
  totalCAFProcessingFee: any,
  totalCAFVB: any
}

export default ConnCommsRcti;